#!/usr/bin/env node
/**
 * Regenerates src/data/revenue-snapshot.json from Stripe.
 *
 *   STRIPE_RESTRICTED_KEYS='{"wanderlust":"rk_live_..."}' node scripts/refresh-revenue.mjs
 *   npm run revenue:refresh
 *
 * The snapshot is what the site renders when no Stripe keys are present at
 * build time, so committing a fresh one keeps the published figures current
 * even without wiring credentials into the deploy.
 */
import { readFile, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import { trackedProjects } from '../src/lib/stats/projects.mjs'
import { fetchRevenueFromStripe } from '../src/lib/stats/stripe.mjs'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const snapshotPath = resolve(root, 'src/data/revenue-snapshot.json')

const COMMENT =
  'Generated by scripts/refresh-revenue.mjs from Stripe. All amounts are in ' +
  'minor units (cents). Do not hand-edit — run `npm run revenue:refresh`.'

/** Loads .env / .env.local without adding a dotenv dependency. */
async function loadEnvFiles() {
  for (const file of ['.env', '.env.local']) {
    let contents
    try {
      contents = await readFile(resolve(root, file), 'utf8')
    } catch {
      continue
    }

    for (const line of contents.split('\n')) {
      const match = line.match(/^\s*([\w.-]+)\s*=\s*(.*)$/)
      if (!match) continue
      const [, key, rawValue] = match
      if (process.env[key]) continue
      process.env[key] = rawValue.trim().replace(/^["']|["']$/g, '')
    }
  }
}

function money(minorUnits, currency = 'usd') {
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: currency.toUpperCase(),
  }).format(minorUnits / 100)
}

async function main() {
  await loadEnvFiles()

  const wanted = trackedProjects.filter((project) => project.stripe)

  if (!process.env.STRIPE_RESTRICTED_KEYS) {
    console.error(
      'STRIPE_RESTRICTED_KEYS is not set.\n\n' +
        'Create a restricted key per Stripe account with read access to\n' +
        'Balance transactions, Subscriptions and Account, then set them as a\n' +
        'JSON object keyed by project id in .env.local:\n\n' +
        `  STRIPE_RESTRICTED_KEYS='${JSON.stringify(
          Object.fromEntries(wanted.map((p) => [p.id, 'rk_live_...'])),
        )}'\n`,
    )
    process.exit(1)
  }

  if (!wanted.length) {
    console.error(
      'No project in src/lib/stats/projects.mjs has a `stripe` entry, so there\n' +
        'is nothing to publish. Add `stripe: { accountId: "acct_..." }` to the\n' +
        'projects whose revenue should be public.',
    )
    process.exit(1)
  }

  console.log(`Fetching ${wanted.length} Stripe account(s)…`)
  const report = await fetchRevenueFromStripe(trackedProjects)

  const snapshot = { $comment: COMMENT, ...report }
  await writeFile(snapshotPath, `${JSON.stringify(snapshot, null, 2)}\n`)

  console.log(`\nWrote ${report.projects.length} account(s) to ${snapshotPath}`)
  for (const project of report.projects) {
    const latest = project.monthly.at(-1)?.net ?? 0
    console.log(
      `  ${project.projectId.padEnd(24)} ` +
        `lifetime net ${money(project.lifetime.net, project.currency)}  ` +
        `${report.months.at(-1)} net ${money(latest, project.currency)}  ` +
        `MRR ${money(project.mrr, project.currency)} ` +
        `(${project.activeSubscriptions} active sub${
          project.activeSubscriptions === 1 ? '' : 's'
        })`,
    )

    if (!project.verified) {
      console.warn(
        `    ! NOT verified against ${project.accountId ?? 'the registry'} — ` +
          'this key was not confirmed to belong to that account',
      )
    }
    if (!project.lifetimeComplete) {
      console.warn(
        `    ! history too long to read in full — lifetime is a lower bound`,
      )
    }
    if (!project.monthlyComplete) {
      console.warn(
        `    ! history did not reach ${report.months[0]} — the 12-month series is incomplete`,
      )
    }
    if (project.otherCurrency) {
      console.warn(
        `    ! ${project.otherCurrency} transaction(s) in other currencies were excluded`,
      )
    }
  }

  const missing = wanted.filter(
    (project) => !report.projects.some((row) => row.projectId === project.id),
  )
  if (missing.length) {
    console.warn(
      `\nWarning: no data returned for ${missing.map((p) => p.id).join(', ')}.\n` +
        'Those projects will render as "not published" until a working key is set.',
    )
  }
}

main().catch((error) => {
  console.error(error)
  process.exit(1)
})
